# Generated by Django 5.2.5 on 2025-11-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodapplication',
            name='beneficiaries_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodapplication',
            name='preferred_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
