# Generated by Django 5.2.5 on 2025-11-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='category',
            field=models.CharField(choices=[('COOKED', 'Cooked Meal'), ('PACKAGED', 'Packaged Food'), ('FRESH', 'Fresh Produce'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='pickup_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='pickup_time_window',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
