# Generated by Django 5.2.8 on 2025-11-06 00:04

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_plan_price', models.DecimalField(decimal_places=2, default=10.0, help_text="The monthly price for the 'Pro' subscription", max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(help_text="User's full name or organization name", max_length=255)),
                ('email', models.EmailField(help_text="User's unique email address", max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Donor', 'Donor'), ('Receiver', 'Receiver'), ('Admin', 'Admin'), ('Main Admin', 'Main Admin')], default='Donor', help_text="User's role in the system", max_length=20)),
                ('phone', models.CharField(blank=True, help_text="User's contact phone number", max_length=20)),
                ('address', models.TextField(blank=True, help_text="User's physical address")),
                ('is_verified', models.BooleanField(default=False, help_text='Flag to indicate if the user is trusted')),
                ('subscription_status', models.CharField(choices=[('Basic', 'Basic'), ('Pro', 'Pro')], default='Basic', help_text='Determines access to premium features', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Server-side timestamp of when the user was created')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(help_text='Name of the food item', max_length=255)),
                ('quantity', models.CharField(help_text='Description of the quantity', max_length=255)),
                ('category', models.CharField(choices=[('Produce', 'Produce'), ('Baked Goods', 'Baked Goods'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Canned Goods', 'Canned Goods'), ('Other', 'Other')], help_text='Category of the food item', max_length=20)),
                ('best_before_date', models.DateTimeField(help_text='The best-before date for the food item')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Claimed', 'Claimed'), ('PickedUp', 'PickedUp'), ('Expired', 'Expired')], default='Available', help_text='Current status of the donation', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Photo of the donation', null=True, upload_to='donation_images/')),
                ('image_hint', models.CharField(blank=True, help_text='AI-powered image search keywords', max_length=255)),
                ('location_lat', models.FloatField(blank=True, help_text='Latitude for geolocation', null=True)),
                ('location_lng', models.FloatField(blank=True, help_text='Longitude for geolocation', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Server-side timestamp of when the donation was posted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Server-side timestamp for the last update')),
                ('claimed_by', models.ForeignKey(blank=True, help_text='The user who claimed the donation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_donations', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(help_text='The user who donated the item', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
